"""Initial migration

Revision ID: 4c58bf6f853
Revises: None
Create Date: 2018-04-29 14:05:59.727989

"""

# revision identifiers, used by Alembic.
revision = '4c58bf6f853'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('address',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('street', sa.String(length=120), nullable=True),
                    sa.Column('postal_code', sa.String(
                        length=120), nullable=True),
                    sa.Column('city', sa.String(length=120), nullable=True),
                    sa.Column('country', sa.String(length=120), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('brand',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.String(length=120), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('product',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('brand_id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.String(length=120), nullable=False),
                    sa.Column('created', sa.DateTime(), nullable=False),
                    sa.ForeignKeyConstraint(
                        ['brand_id'], ['brand.id'], onupdate='CASCADE', ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('supermarket',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.String(length=120), nullable=False),
                    sa.Column('address_id', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(
                        ['address_id'], ['address.id'], onupdate='CASCADE', ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('product_supermarket',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('product_id', sa.Integer(), nullable=False),
                    sa.Column('supermarket_id', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(
                        ['product_id'], ['product.id'], onupdate='CASCADE', ondelete='CASCADE'),
                    sa.ForeignKeyConstraint(['supermarket_id'], [
                        'supermarket.id'], onupdate='CASCADE', ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('id')
                    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('product_supermarket')
    op.drop_table('supermarket')
    op.drop_table('product')
    op.drop_table('brand')
    op.drop_table('address')
    ### end Alembic commands ###
